version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: angel
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: budget_beacon
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: